### ISSUE TITLE
Correctness check for extension 1

### ISSUE THREAD

**Issue by dstrueber** [sinemgetir/state-elimination-mt#2]
I have a question concerning the correctness check for extension 1:

`A solution to the first extension task (see Section 3.2) is correct if the produced model represents a uniform
FSA  which  is  equivalent  to  the  one  provided  as  input.   This  can  be  confirmed  by  checking  equality  of  the
resulting model to the one produced by the reference implementation using JFLAP. This correctness test may
be automated using the model comparison tool EMF Compare [BP08], which should report no changes between
a produced output model and the corresponding reference output model.`

Technically, the issue here is that the JFLAP implementation seems to use its own data structure to represent the FSA, which lives outside the EMF world (automata.fsa.FiniteStateAutomaton).  I assume it's not the idea that every solution provides its own JFLAP-to-EMF-transformation just to enable the correctness check, right? Is there an available transformation we can use?

**Comment by dstrueber** [comment]
Also, the test models for extension 1 are only provided in the JFLAP format. Since the code for parsing and loading this format into an EMF-based model would be the same for each EMF-based solution, I wonder if this code is available.

**Comment by sinemgetir** [comment]
We have uploaded the EMF project which includes the transformations for between tra-EMF format.
https://github.com/sinemgetir/state-elimination-mt/tree/master/Tra2Emf 

it is a simple and small utility to convert tra files into EMF models being instances of our 
generic transition graph meta-model for representing FSAs, CTGs and PAs.

The Eclipse project containts a class Tra2Emf which has a main method.

Arguments should be: <input-dir> <output-dir> [FSA|PA] [true|false]
    - <input-dir> folder containing all the tra-files to be converted
    - <output-dir> folder where the EMF models (xmi-files) should be written to.
    - [FSA|PA] Whether to interprete the automaton as finite state machine (FSA) or probabilistic automaton (PA)
    - [true|false] Whether the automaton is uniform (true) or not (false)



Also we have now the corresponding EMF instance models wrt to Extension 1 under the folder
https://github.com/sinemgetir/state-elimination-mt/tree/master/ExperimentalData/testdata/emf/task-extension1


Thank you very much for your questions.

**Comment by dstrueber** [comment]
Thanks! This utility is really helpful and almost solves the problem. There is only one puzzle piece missing:

For the evaluation of extension 1, we have to compare the output of our tool to the output of the JFLAP implementation. The Tra2Emf utility can make the JFLAP output ready for this comparison, **assuming it's available as a tra-file**. However, the question is how this assumption can be realized. While there is a method for producing the output of extension 1 (FSAToRegularExpressionConverter.convertToSimpleAutomaton()), I can't seem to find a method for saving this output as a tra-file. Am I overlooking this method?

**Comment by dstrueber** [comment]
I noticed another issue: According to the case description (page 6), the input for extension 1 is a "non-uniform FSA containing _multiple_ initial and final states." However, the FiniteStateAutomaton data structure used by the reference solution [1] supports just _one_ initial and multiple final states. Based on this data structure, I wonder how the reference solution would be able to produce a correct solution that can be used as a ground truth to evaluate extension 1 solutions.

[1] FSAToRegularExpressionConverter.convertToSimpleAutomaton(FiniteStateAutomaton)

**Comment by vuducanh1112** [comment]
We provided a small method to transform a JFLAP FSA into a .tra file. You can find it in the class state-elimination-mt/EvaluationFramework/src/experiment/FSAToTraConverter.java

Thanks

**Comment by dstrueber** [comment]
Thanks! Any ideas regarding my comment from May 25?

**Comment by vuducanh1112** [comment]
Your are right, JFLAP does not support this task directly. To check the correctness of solutions, we provided the class 
state-elimination-mt/EvaluationFramework/src/experiment/TransitionGraphUniformer.java .
Thank you.
