### ISSUE TITLE
Scalability evaluation: timeout

### ISSUE THREAD

**Issue by dstrueber** [sinemgetir/state-elimination-mt#4]
Since timeouts usually happen after a user-specified time duration, it seems like a good idea if all solutions used the same duration as the reference solution. However, neither the paper nor the test framework specifies a duration. Any suggestions on which duration to use?

**Comment by sinemgetir** [comment]
Hi, we ran the experiments for 1 hour. so we can use this duration as a reference.

**Comment by dstrueber** [comment]
"we ran the experiments for 1 hour" - Does this mean 1 hour for all models, or 1 hour per model? In the first case, please also specify the order in which you considered the models (since there are some cases of smaller models which come alphabetically later than the larger ones).

**Comment by snmgtr** [comment]
Actually it is the second case. max 1 hour per model. we run them in the order of size (number of states).

**Comment by dstrueber** [comment]
I see, thanks. This resolve the issue for me.
